import { useState } from "react";
import Layout from "../components/Layout";
import Head from "next/head";
import Image from "next/image";
import AddNewMessage from "../components/AddNewMessage";
import MessagesList from "../components/MessagesList";
import logo from "../public/favicon.png";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [reloadData, setReloadData] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Tweety</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <AddNewMessage reloadData={reloadData} setReloadData={setReloadData} />
          <MessagesList reloadData={reloadData} setReloadData={setReloadData} />
        </main>
      </Layout>
    </div>
  );
}